### ISSUE TITLE
thumbnail position is off

### ISSUE THREAD

**Issue by efreeman518** [Teyuto/videojs-vtt-thumbnails#11]
Can you tell why the thumbnail is shifted farther to the right depending on how wide the browser is sized?
https://wwwtest.siriusjoy.com/1/ef-pl-1

**Comment by marcellov7** [comment]
@efreeman518 
The plugin works correctly on our end.
https://academy.teyuto.tv/video/player?w=46761
You should check for any conflicts with the CSS and ensure that your thumbnails are the correct size (consult the code inside the example).
If you find the issue, feel free to submit a pull request.

**Comment by antonypetras** [comment]
Same issue here.
See https://github.com/Teyuto/videojs-vtt-thumbnails/pull/12
